server:
  port: 8081
spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/yoaotu_template?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    url: jdbc:mysql://139.196.235.51:3306/member?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: member
    #    username: root
    password: 3GKykt83ayKC3nJN
    #    password: Dya110699++
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 139.196.235.51
    port: 6480
    database: 0
    timeout: 3000
    password: Q9KM-H#39xg8]mDKcyH%
logging:
  level:
    com.gitee.sunchenbin.mybatis.actable.dao: debug
    com.youaodu.template.common.dao.mapper: debug
